FROM pull ghcr.io/puppeteer/puppeteer:24.21.0 
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY src/ ./src/
CMD ["npm", "start"]